modLoader="javafml"
loaderVersion="[30,)"

[[mods]]
    modId="aquaculture"
    version="${file.jarVersion}"
    displayName="Aquaculture 2"
    displayURL="https://minecraft.curseforge.com/projects/aquaculture"
    issueTrackerURL="https://github.com/TeamMetallurgy/Aquaculture/issues"
    authors="Shadowclaimer, Girafi"
    credits="Glassmaker, lclc98, Freyja, and Rebelkeithy"
    description='''
    Welcome to Aquaculture! An expansion of Minecraft's fishing system.
    '''

[[dependencies.aquaculture]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.51,)"
    ordering="AFTER"
    side="BOTH"